name: Update Elastic release

on:
  schedule:
    - cron: '0 0 * * 0'  # At 00:00 every Sunday

jobs:

  check-and-update:
    name: Check and update Elastic release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - 7.x
          - 6.x
        include:
          - release: 7.x
            branch: main
          - release: 6.x
            branch: release-6.x

    steps:
      - uses: actions/setup-node@v2
      - run: npm install semver

      - name: Get latest release version
        uses: actions/github-script@v5
        id: get-latest-release
        with:
          script: |
            const semver = require('semver')

            const latestVersion = await github.
              paginate(github.rest.repos.listReleases, {
                owner: 'elastic',
                repo: 'elasticsearch'
              })
              .then(releases => {
                for (const release of releases) {
                  // Results are returned sorted by created_at, so it is safe to assume
                  // that the first encountered match is also the series' latest release.

                  const version=semver.clean(release.tag_name)

                  if (semver.satisfies(version, '${{ matrix.release }}')) {
                    return version
                  }
                }
              });

            if (latestVersion) {
              // Return an object so that the result can be handled as structured data
              // instead of a quoted string in subsequent steps.
              return { version: latestVersion }
            }

      - uses: actions/checkout@v2
        if: steps.get-latest-release.outputs.result
        with:
          ref: ${{ matrix.branch }}

      - name: Update stack version
        id: update-files
        if: steps.get-latest-release.outputs.result
        run: |
          source .env
          cur_ver="$ELK_VERSION"
          new_ver=${{ fromJson(steps.get-latest-release.outputs.result).version }}

          # Escape dot characters so sed interprets them as literal dots
          cur_ver="$(echo $cur_ver | sed 's/\./\\./g')"

          for f in .env docker-stack.yml README.md; do
              sed -i "s/${cur_ver}/${new_ver}/g" "$f"
          done

          git_status="$(git status --porcelain)"
          if [[ ${git_status} ]]; then
              echo -e 'Changes to be committed:\n'
              echo "${git_status}"
              echo '::set-output name=has_changes::true'
          fi

      - name: Impersonate update bot
        uses: tibdex/github-app-token@v1
        id: generate-token
        if: steps.update-files.outputs.has_changes
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Send pull request to update to new version
        if: steps.update-files.outputs.has_changes
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update/${{ matrix.branch }}
          commit-message: Update to v${{ fromJson(steps.get-latest-release.outputs.result).version }}
          title: Update to v${{ fromJson(steps.get-latest-release.outputs.result).version }}
          delete-branch: true
